### ISSUE TITLE
I have a question about your blade views

### ISSUE THREAD

**Issue by filipveschool** [l5starter/permission-manager#2]
Hi,

Why do you use in your blade view files inside the @extends 'l5starter::' :
`
@extends('l5starter::admin.layouts.master')
`

Like mentioned here above. Why and how do you do that? I have never seen that before?

**Comment by wiwatsrt** [comment]
I used layout from package `l5starter/core` 

`l5starter` : Vendor name
`admin.layouts.master` : File path

In code
``` php
$this->loadViewsFrom(__DIR__.'/../resources/views', 'l5starter');
```
